fix(syslog): add logrotate 'su root adm' directive
/var/log is owned root:adm (group-writable), which causes logrotate to
skip all log files in that directory with:

  error: skipping "/var/log/..." because parent directory has insecure
  permissions (It's world writable or writable by group which is not
  "root") Set "su" directive in config file to tell logrotate which
  user/group should be used for rotation.

Fix by inserting 'su root adm' into /etc/logrotate.conf before the
include /etc/logrotate.d line, and into /etc/logrotate-dmesg.conf
before the /var/log/dmesg stanza, during syslog configure. This tells
logrotate to run as root:adm, which has the necessary permissions to
safely rotate files under /var/log.

Also add verify checks that the directive is present in both files.

Signed-off-by: Mark Silva <mark.silva@emerson.com>